name = "Weilu Wang"
license = "YangZhou University"
licenselink = "https://github.com/htr3n/hyde-hyde/blob/master/LICENSE.md"
description = "A simply cool Hyde inspired theme"
tags = ["blog", "theme", "hyde", "highlight.js", "font-awesome", "google analytics", "disqus", "personal", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "highlight.js", "font-awesome", "responsive", "disqus", "graphcomment", "portfolio"]
homepage = "https://github.com/wangdata/wangblog.com"
min_version = "0.33"

[author]
    name = "WWL"
    homepage = "https://philipwang.netlify.com"

# If Porting existing theme
[original]
    author =  "spf13"
    homepage = "http://spf13.com/"
    repo = "https://github.com/spf13/hyde"
